### ISSUE TITLE
Add Mobile-Only Navigation Menu for Improved Mobile Usability

### ISSUE THREAD

**Issue by Ashish93-mrx** [neerajrathore/javascript-handbook#104]
### Is this a unique topic?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your topic request related to a problem/unavailable functionality? Please describe.

The application does not currently have a dedicated navigation menu(Introduction, Topics, Share, Contact Us) for mobile devices, which makes it challenging for mobile users to navigate between sections. This lack of navigation can result in a poor user experience on smaller screens.

### Proposed Solution

I propose adding a responsive sidebar navigation menu that will only appear on mobile devices. This menu will include links to major sections, making it easier for mobile users to navigate. The navigation will be hidden on larger screens, ensuring that the desktop experience remains unchanged. I plan to implement this using media queries to detect screen size and toggle the mobile menu as needed.

### Screenshots

![Screenshot 2024-10-16 185320](https://github.com/user-attachments/assets/85a8fdab-e22b-42e5-8e53-39792adf23b3)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I will use media queries to conditionally render the mobile navigation component only on screens below a certain width. This way, the navigation will only appear for mobile users, and the web/desktop layout will remain the same. I’ll ensure the menu is responsive and easy to use with touch gestures.

**Comment by neerajrathore** [comment]
@Ashish93-mrx are you making any progress?

**Comment by Ashish93-mrx** [comment]
> @Ashish93-mrx are you making any progress?

yes i'm almost finished, i will pull request today.

**Comment by Ashish93-mrx** [comment]
> @Ashish93-mrx are you making any progress?

i have done the pull request, you can review now.
