### ISSUE TITLE
Improving the Nav bar and adding hover effects on nav bar

### ISSUE THREAD

**Issue by smritig26** [neerajrathore/javascript-handbook#107]
### Is this a unique topic?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your topic request related to a problem/unavailable functionality? Please describe.

Its related to nav bar

### Proposed Solution

I wish to add hover effects and enhance the UI of the nav bar

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I wish to implement this with the help of HTML and CSS features in order to have advanced hover effects

**Comment by neerajrathore** [comment]
@smritig26 are you making any progress?
