### ISSUE TITLE
Array methods

### ISSUE THREAD

**Issue by lord-cyclone100** [neerajrathore/javascript-handbook#11]
Hello @neerajrathore 
I would like to add notes and code snippets of javascript array methods.
I would like to contribute in your repository and so pls assign me this task under hacktoberfest

**Comment by neerajrathore** [comment]
Hello 👋! Thank you very much for raising an issue! 

You can go ahead with your contribution 🚀.

**Comment by lord-cyclone100** [comment]
@neerajrathore Bro I would love to contribute in your project but pls make sure to put the hacktoberfest label 😊

**Comment by neerajrathore** [comment]
@lord-cyclone100 array methods like Map() , filter() , reduce() is already added. check #20 

you can add methods that are not covered yet. Also check topics list #10
