### ISSUE TITLE
Equality Comparison

### ISSUE THREAD

**Issue by mohitahlawat2001** [neerajrathore/javascript-handbook#12]
### == vs ===: 
Type conversion in == and why === is safer. examples
### Object Comparison:
 Why object comparison behaves differently. exmples

**Comment by ajay0180** [comment]
hey, I want to contribute to this issue. But , before that can you add hacktoberfest and hacktoberfest-accepted label with this issue.

**Comment by mohitahlawat2001** [comment]
please assign me this issue @neerajrathore

**Comment by neerajrathore** [comment]
Hello @mohitahlawat2001  👋! Thank you very much for raising an issue! Your efforts will help increase knowledge of fellow peers.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

I'm excited to see your contribution as part of Hacktoberfest 2024! 🎉

Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
