### ISSUE TITLE
feat: Want to add promise topic

### ISSUE THREAD

**Issue by realvishalrana** [neerajrathore/javascript-handbook#17]
@neerajrathore please assign me under hacktoberfest

**Comment by neerajrathore** [comment]
@realvishalrana  This topic is already covered in PR #15 . You can contribute other topics of JavaScript.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

I'm excited to see your contribution as part of Hacktoberfest 2024! 🎉

Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
