### ISSUE TITLE
Enhance the UI of the website

### ISSUE THREAD

**Issue by bhaavvya** [neerajrathore/javascript-handbook#18]
An beautiful and innovative ui of website will attract learners to come to the platform and study.

@neerajrathore ,Please assign me this issue under hacktoberfest 2024 and open for any suggestion

**Comment by neerajrathore** [comment]
@bhaavvya you can go ahead with UI changes.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach before & after screenshots in your PR for clarity.
- Include the issue number in your PR description for better tracking.

I'm excited to see your contribution as part of Hacktoberfest 2024! 🎉

Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by Ehm-Ehs** [comment]
Hi @neerajrathore i would like to join @bhaavvya  in enhancing the ui. kindly assign

**Comment by neerajrathore** [comment]
@Ehm-Ehs you can raise another issue if you want to work on UI as well.

**Comment by neerajrathore** [comment]
@bhaavvya  I hope you are making progress. If you need any help or suggestion, let me know.

**Comment by bhaavvya** [comment]
@neerajrathore , yes I will be opening a PR at the EOD.
