### ISSUE TITLE
Add a dark mode 

### ISSUE THREAD

**Issue by SiddhanthKapoor** [neerajrathore/javascript-handbook#19]
The website currently lacks a dark mode feature, which is increasingly becoming a standard for modern web design. Dark mode offers an alternative theme, providing a darker color scheme for improved readability in low-light conditions and reducing eye strain. This functionality should allow users to switch between light and dark modes, either manually or automatically based on system settings.

I would like to work on creating a dark mode toggle for this website !

**Comment by neerajrathore** [comment]
@SiddhanthKapoor you can go ahead with your contribution.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Include the issue number in your PR description for better tracking.

I'm excited to see your contribution as part of Hacktoberfest 2024! 🎉

Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by AADESHak007** [comment]
hey @SiddhanthKapoor @neerajrathore  may I work in this issue ?

**Comment by neerajrathore** [comment]
@SiddhanthKapoor Are you making any progress?

**Comment by SiddhanthKapoor** [comment]
> @SiddhanthKapoor Are you making any progress?

Yes ! I will be making a PR within a day or two.

**Comment by SiddhanthKapoor** [comment]
> @SiddhanthKapoor Are you making any progress?

I would like you to unassign me this issue.

**Comment by AADESHak007** [comment]
Hey @SiddhanthKapoor I would like to create a dark mode for this .

**Comment by neerajrathore** [comment]
@AADESHak007 you can work on this issue

**Comment by YockerFX** [comment]
There is already a dark mode Design…

![](https://cdn.discordapp.com/attachments/1277939534851604520/1291065949008433293/image.png?ex=6709f31d&is=6708a19d&hm=306621b00ef7f81d12056106233c7522aad3a74f8e859ae488fd16b254997490&)
![](https://cdn.discordapp.com/attachments/1277939534851604520/1291065872298938491/image.png?ex=6709f30a&is=6708a18a&hm=35df1ee0b5abeec5c893edc9d80b68898b90e1cb71a4e28e865e36ef843f8f11&)

**Comment by AADESHak007** [comment]
@YockerFX I saw that when I was browsing for ideas . I ll raise a PR till saturday night , I would be happy to recieve some feedback .

**Comment by neerajrathore** [comment]
@AADESHak007 Are you making any progress?

**Comment by AADESHak007** [comment]
@neerajrathore Sorry brother took a lot of time . I am working on it right now will raise a PR by today .
