### ISSUE TITLE
Want to create an about us component for the website 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [neerajrathore/javascript-handbook#22]
I want to create the about us component for the website where user can get the details about the project

**Comment by neerajrathore** [comment]
@Ayushmaanagarwal1211 you can go ahead with your contribution.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Include the issue number in your PR description for better tracking.

I'm excited to see your contribution as part of Hacktoberfest 2024! 🎉

Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
