### ISSUE TITLE
MAKE A CRUD API IN NODE.JS

### ISSUE THREAD

**Issue by Arpit529Srivastava** [neerajrathore/javascript-handbook#29]
I would like create a crud api code, so that it learn more about api, routes, node.js framework

@neerajrathore please review this and add the label as hactoberfest

**Comment by vverma022** [comment]
Can I work on this issue under Hacktoberfest 24

**Comment by neerajrathore** [comment]
@Arpit529Srivastava You can proceed with your contribution.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Include the issue number in your PR description for better tracking.

I'm excited to see your contribution as part of Hacktoberfest 2024! 🎉

Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by neerajrathore** [comment]
@vverma022 issue assign to first come basis. You can contribute other topics as well.

**Comment by Arpit529Srivastava** [comment]
@neerajrathore please merge the PR and add the label ```hactoberfest-accepted```

**Comment by neerajrathore** [comment]
@Arpit529Srivastava your pr #45 does not qualify hacktoberfest.

you can add topics of javascript.
