### ISSUE TITLE
[Add] Add Software Design Patterns in JavaScript to the Project

### ISSUE THREAD

**Issue by suryanshsingh2001** [neerajrathore/javascript-handbook#35]
## Description
I want to expand the project by adding well-documented examples of popular software design patterns implemented in JavaScript. These examples will serve as a reference for other developers who are interested in understanding and implementing these patterns in their JavaScript projects.

## Patterns to Implement

- [ ] Singleton
- [ ] Factory
- [ ] Observer
- [ ] Module
- [ ] Adapter
- [ ] Composite

## Requirements
1. Each design pattern should be implemented in JavaScript.
2. Include a detailed `design-patterns/README.md` for each pattern that explains:
   - What problem the pattern solves.
   - The implementation in JavaScript.
   - Example usage of the pattern.
3. Provide test cases for each pattern to demonstrate its usage.
4. Code must follow the existing code style and should be properly linted.

## Why This is Needed
Adding software design patterns will greatly benefit developers by helping them understand different problem-solving approaches in JavaScript and improve the architecture of their codebase.

## Acceptance Criteria
- Each design pattern is properly implemented in JavaScript.
- All examples have a descriptive README explaining the pattern, its purpose, and a usage example.
- Tests for each pattern demonstrate how to use the pattern in practice.

**Comment by suryanshsingh2001** [comment]
Hey @neerajrathore, Please assign me this issue.

**Comment by neerajrathore** [comment]
@suryanshsingh2001 you can go ahead with your contribution.

Knowledge of software design patterns is undoubtedly helpful for job advancement.
