### ISSUE TITLE
Adding Advanced JS Concepts like Currying

### ISSUE THREAD

**Issue by shrinjayshresth1** [neerajrathore/javascript-handbook#38]
Hi @neerajrathore 
I wish to Create a comprehensive guide to currying in JavaScript can be very beneficial for understanding functional programming concepts. 
 Proposed Structure
1. ****Introduction to Currying**:
   - Definition and basic concept.
   - Difference between currying and partial application.

2. **Basic Syntax and Examples**:
   - Simple examples to illustrate currying.
   - Step-by-step breakdown of how currying works.

3. **Implementing Currying**:
   - Manual implementation of a curry function.
   - Using existing libraries (e.g., Lodash).

4. **Use Cases and Benefits**:
   - Real-world scenarios where currying is useful.
   - Benefits of using currying in functional programming.

5. **Advanced Currying Techniques**:
   - Handling multiple arguments.
   - Currying with variadic functions.

6. **Common Pitfalls and How to Avoid Them**:
   - Potential issues when using currying.
   - Best practices to follow.

7. **Practical Applications**:
   - Examples of currying in popular frameworks and libraries.
   - Integrating currying into existing projects.

8. **Comparison with Other Functional Programming Techniques**:
   - How currying compares to other techniques like closures and higher-order functions.

I would like this issue to be assigned to me.

**Comment by neerajrathore** [comment]
@shrinjayshresth1 You can proceed with your contribute.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Include the issue number in your PR description for better tracking.

I'm excited to see your contribution as part of Hacktoberfest 2024! 🎉

Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by neerajrathore** [comment]
@shrinjayshresth1 Are you making any progress?

**Comment by shrinjayshresth1** [comment]
Just Saw Currying is already added. How is it possible since it was assigned to me.
