### ISSUE TITLE
Readme preview broken for topics 8-12

### ISSUE THREAD

**Issue by chaitanya-bhargava** [neerajrathore/javascript-handbook#40]
The topics 8-12 are not showing correctly on the hosted link.

![Screenshot 2024-10-02 151540](https://github.com/user-attachments/assets/6ced4f39-b801-41f2-bc8f-a9ee2c64db8a)

I can fix this issue. Please assign it to me!

**Comment by neerajrathore** [comment]
@chaitanya-bhargava . You can solve the issue as well contribute other topics of JavaScript. see #10 for list of topics

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Include the issue number in your PR description for better tracking.

I'm excited to see your contribution as part of Hacktoberfest 2024! 🎉

Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
