### ISSUE TITLE
Adding Navbar

### ISSUE THREAD

**Issue by anamelahi** [neerajrathore/javascript-handbook#44]
The website currently lacks a navbar and a 'search' feature. The navbar should include the website's name (or logo), a link to the GitHub repository (for contributions), and a search button (to search for topics). 

I would like to be assigned this feature.

**Comment by rajchaudhary99** [comment]
Please assign me the task of adding a navbar to the website. I’m prepared to begin working on it!

**Comment by neerajrathore** [comment]
@rajchaudhary99 issue assignment is done on first come first get basis. You can create another issue for the topic you want to work on.

**Comment by neerajrathore** [comment]
@anamelahi  You can proceed with your contribution.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Include the issue number in your PR description for better tracking.

I'm excited to see your contribution as part of Hacktoberfest 2024! 🎉

Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by anamelahi** [comment]
Hey @neerajrathore , Thankyou for assigning me this feature. The repository only has .md files and I couldn't find the files for the website.
Can you help me locate the code for the website ?
Also please add the label for hacktoberfest.

**Comment by neerajrathore** [comment]
@anamelahi you can checkout branch [ui/patch-pr-47](https://github.com/neerajrathore/javascript-handbook/tree/ui/patch-pr-47)
