### ISSUE TITLE
Add a search bar

### ISSUE THREAD

**Issue by sanskriti49** [neerajrathore/javascript-handbook#48]
The site currently lacks styling a bit, I would love to rework the whole design  improve the overall aesthetics, and  a 'search' feature to make it easier for users to search for the relevant topics or even sub-topics,  will enhance user navigation and searchability within the site.

Please assign me under hacktober!

**Comment by neerajrathore** [comment]
@sanskriti49 indeed search functionality will help finding topic fast and easy. You can proceed with your contribution.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Include the issue number in your PR description for better tracking.

I'm excited to see your contribution as part of Hacktoberfest 2024! 🎉

Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by neerajrathore** [comment]
@sanskriti49 I hope you are making progress. If you need any help or suggestion, let me know.
