### ISSUE TITLE
feat: add footer for social media icons

### ISSUE THREAD

**Issue by realvishalrana** [neerajrathore/javascript-handbook#49]
Please assign this issue under hacktoberfest

**Comment by rajchaudhary99** [comment]
Please assign the issue of adding social media icons to the footer to me. I’m ready to get started!

**Comment by neerajrathore** [comment]
@realvishalrana You can proceed with your contribution.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Include the issue number in your PR description for better tracking.

I'm excited to see your contribution as part of Hacktoberfest 2024! 🎉

Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by realvishalrana** [comment]
@neerajrathore can you please add hacktoberfest accepted label
