### ISSUE TITLE
share button

### ISSUE THREAD

**Issue by Ashish93-mrx** [neerajrathore/javascript-handbook#54]
i would like to add a share button so people can easily share to tweet, linkedin etc.

**Comment by Ashish93-mrx** [comment]
pls assign me this task under hacktoberfest.

**Comment by neerajrathore** [comment]
@Ashish93-mrx You can proceed with your contribution.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Include the issue number in your PR description for better tracking.

I'm excited to see your contribution as part of Hacktoberfest 2024! 🎉

Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by Ashish93-mrx** [comment]
@neerajrathore i have made the pull request please review #54 and for this issue 'hacktoberfest' label is not added, i wanted this as hacktoberfest contribution :(.
