### ISSUE TITLE
Adding content of call(),bind() and apply()

### ISSUE THREAD

**Issue by Arushi-N4** [neerajrathore/javascript-handbook#63]
### Is this a unique topic?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

There is often confusion surrounding the differences between `call()`, `apply()`, and `bind()`, especially in how they handle passing arguments to functions. Learners may get confused on when to use each method.

### Proposed Solution
I would like to make content for learners about this topic to get clear understanding and avoid confusion

### Do you want to work on this issue?
Yes

### Please explain how you would technically implement this

1. Creating new folder called `call,bind and apply`
2. Making readme file
3. Making content on what is  `call()`, `apply()`, and `bind()` ( what is it ,syntax ,uses with example ,how it differs from each other ,when to use ,discuss how each method deals with argument passing in functions, and which method is most appropriate in specific cases)

**Comment by neerajrathore** [comment]
@Arushi-N4 you can start your contribution.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes from main branch to avoid any merge conflicts.
- Include the issue number in your PR description for better tracking.

I'm excited to see your contribution as part of Hacktoberfest 2024! 🎉

Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by neerajrathore** [comment]
@Arushi-N4  Are you making any progress?

**Comment by Arushi-N4** [comment]
Apologies for the delayed response!
I’ve been busy with my exams. I’ve now completed the content and am working on committing the changes and connecting everything to the frontend. Thanks for your patience
