### ISSUE TITLE
[Currying] <Add Currying Topic to the Handbook>

### ISSUE THREAD

**Issue by ArpitCS** [neerajrathore/javascript-handbook#65]
### Is this a unique topic?

- [x] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your topic request related to a problem/unavailable functionality? Please describe.

I often find it challenging to convey the benefits and usage of advanced JavaScript concepts, such as currying. Many developers struggle with understanding the difference between currying and partial application, and how these concepts can enhance code reusability and readability. Additionally, existing resources often lack practical examples demonstrating how to implement these concepts in real-world scenarios.

### Proposed Solution

I propose adding a topic on **Currying in JavaScript** to the JavaScript Handbook. This topic will cover:

- **Why Currying is Useful**: Explanation of how currying helps in creating more reusable and composable functions.
- **Comparison with Partial Application**: Clarifying the differences between currying and partial application with examples.
- **Practical Implementation**: A simple project demonstrating the advantages of currying through a **Functional Discount Calculator** that dynamically applies discount rates to product prices.

The implementation of this topic can draw inspiration from other projects and articles focused on functional programming in JavaScript. For example, the article on [Understanding Currying](https://medium.com/javascript-scene/currying-in-javascript-81eb7e142cb4) provides a foundational understanding that can be expanded upon with hands-on examples.

### Screenshots

![Screenshot 2024-10-06 235920](https://github.com/user-attachments/assets/0a256714-a9f2-4974-904a-9804fca23566)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

To implement this topic, I will:

1. Create a new section in the JavaScript Handbook dedicated to **Currying in JavaScript**.
2. Write a comprehensive explanation of what currying is and why it's beneficial, along with a comparison to partial application.
3. Develop code examples that illustrate basic currying and partial application, including a practical use case, like the **Functional Discount Calculator**.
4. Ensure that the examples are well-documented and easily understandable for developers at various skill levels.
5. Organize the project files into a clear directory structure, making it easy for contributors to access and understand the implementation.

I will reference existing JavaScript functional programming concepts and use well-established practices to ensure clarity and maintainability.

**Comment by ArpitCS** [comment]
Hi! I've created a pull request to address this issue. You can check it out here: #64 .
Looking forward to your feedback!

Direct Link: https://github.com/neerajrathore/javascript-handbook/pull/64#issue-2568811002

**Comment by ArpitCS** [comment]
Hello @neerajrathore I have already created a Pull Request with respect to this Issue. Please take a look at it and suggest any changes. Please merge if the changes are acceptable.

Pull Request #64

**Comment by neerajrathore** [comment]
@ArpitCS yes I am reviewing your changes now
