### ISSUE TITLE
[add feature] <improve home page and add review page >

### ISSUE THREAD

**Issue by Sahoobarsharani** [neerajrathore/javascript-handbook#77]
### Is this a unique topic?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your topic request related to a problem/unavailable functionality? Please describe.

improve home page and add review page that will help for better user experience .

### Proposed Solution

enhance homepage and add rate us page.  assign this under hacktoberfest

### Do you want to work on this issue?

Yes

**Comment by neerajrathore** [comment]
@Sahoobarsharani  Are you making any progress?

**Comment by Sahoobarsharani** [comment]
yes almost

**Comment by neerajrathore** [comment]
@Sahoobarsharani are you making any progress. To contribute in Hacktoberfest 30th October is the last day. 

If you need any help then let me know

**Comment by Sahoobarsharani** [comment]
i have completed home page and review page i cannot able to do it in one single commit it

**Comment by neerajrathore** [comment]
@Sahoobarsharani Follow these steps-

- delete existing fork and take new fork of this repository in new folder or take a new clone.
- copy all your changes from your old project folder (on your device) to new created folder.
- commit your changes and create PR

**Comment by Sahoobarsharani** [comment]
okay
