### ISSUE TITLE
Add contribution workflow and readme update

### ISSUE THREAD

**Issue by neerajrathore** [neerajrathore/javascript-handbook#80]
### Is this a unique topic?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your topic request related to a problem/unavailable functionality? Please describe.

Auto Add contribution in readme file on successful merge by creating github workflow and readme changes.

### Proposed Solution

@yashksaini-coder can you add those changes?

### Do you want to work on this issue?

No

**Comment by yashksaini-coder** [comment]
@neerajrathore I can implement & add the action workflow. If that's what you want with few markers in Markdown

**Comment by neerajrathore** [comment]
@yashksaini-coder go ahead with your contribution.
