### ISSUE TITLE
Rework the Design

### ISSUE THREAD

**Issue by YockerFX** [neerajrathore/javascript-handbook#9]
Transform Markdown sheets into HTML, CSS & JS Code so that styling is a bit easier. 

I would do that if that is fine for you :)

**Comment by neerajrathore** [comment]
@YockerFX you can start your contribution.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Include the issue number in your PR description for better tracking.

I'm excited to see your contribution as part of Hacktoberfest 2024! 🎉

Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
